name: riverpodcounter
description: A new Flutter application.
version: 1.0.0+1
dependencies:
  flutter:
    sdk: flutter
  flutter_hooks:
  hooks_riverpod:
  state_notifier:
  functional_widget_annotation:
builders:
  functional_widget:
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  functional_widget:
flutter:
  uses-material-design: true
